name: theme_palette_generator
description: "A code generator that automatically creates Flutter ThemeExtensions for custom design systems and color palettes."
version: 0.0.6
repository: https://github.com/Rerurate514/theme_palette_generator
homepage: https://rerurate.com
issue_tracker: https://github.com/Rerurate514/theme_palette_generator/issues

environment:
  sdk: ^3.11.3
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ">=6.0.0 <9.0.0"
  source_gen: ">=4.2.3 <5.0.0"
  code_builder: ">=4.4.0 <5.0.0"
  build: ">=4.0.0 <5.0.0"
  dart_style: ">=2.2.3 <4.0.0"
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
